spring.application.name=SPRING--DISH-MANAGER

spring.datasource.url=jdbc:postgresql://localhost:5432/dish_management_db
spring.datasource.username=dish_manager_user
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver